### ISSUE TITLE
Satellite 6.x localhost?

### ISSUE THREAD

**Issue by platipusica** [stdevel/katprep#119]
Hi there, 

trying this:

katprep_parameters --update-parameters -C xxxx
Authentication container password: 
Enter value for 'katprep_virt' (hint: Virtualization URL of the system): https://xxxxxx
Enter value for 'katprep_mon' (hint: URL of the monitoring system): 
Enter value for 'katprep_virt_snapshot' (hint: Boolean whether system needs to be protected by a snapshot before maintenance): FALSE
WARNING:katprep_shared:Login information for 'localhost' not found in container!
Satellite Username: admin
Satellite Password: 
Traceback (most recent call last):
  File "/usr/bin/katprep_parameters", line 9, in <module>
    load_entry_point('katprep==0.5.0', 'console_scripts', 'katprep_parameters')()
  File "build/bdist.linux-x86_64/egg/katprep/parameters.py", line 376, in cli
  File "build/bdist.linux-x86_64/egg/katprep/parameters.py", line 349, in main
  File "build/bdist.linux-x86_64/egg/katprep/clients/ForemanAPIClient.py", line 84, in __init__
  File "build/bdist.linux-x86_64/egg/katprep/clients/ForemanAPIClient.py", line 256, in validate_api_support
  File "build/bdist.linux-x86_64/egg/katprep/clients/ForemanAPIClient.py", line 207, in api_get
  File "build/bdist.linux-x86_64/egg/katprep/clients/ForemanAPIClient.py", line 174, in __api_request
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'localhost' doesn't match 'yyyyyy'

Not sure how is localhost used instead of yyyyyy? How do we point scripts to DNS name of Satellite server?

Thanks

**Comment by platipusica** [comment]
Solved.

The Docs are not clear about this. All servers are  handled by:

katprep_authconfig mycontainer.auth add

And one need to repeat this for any server used.

Regards
